### PR TITLE
rebuild y-py for python 3.12

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changes:
- [x] runs the test suite under coverage with threshold
- [x] update `pip` invocation
- [x] use same `maturin` as upstream
- [x] manually apply the python 3.12 migration (was unsolveable due to old maturin pin)
- [x] remove single use `name` variable
- [x] hoist maturin version to a variable  
- [x] use azure for all builds
- [x] add bot inspection for future PRs

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/y-py ready for review

**Review by davidbrochart — APPROVED** [review]

**Review by fcollonval — APPROVED** [review]
Thanks @bollwyvl

**Comment by bollwyvl** [comment]
Thanks! Think the whole stack should be 3.12-ready, with this in.

**Pull request merged**
